#58 の修正
cdlab-sit/XenonText pull request #62
Opened 2020-08-30 06:02 UTC by Sota-Watanabe

2020-08-30 11:35 UTC, Sota-Watanabe commented on src/renderer/reducks/editor/selectors.js
> +import * as utils from './utils';
import する際, 名前がかぶってしまうのでimport * をしているのですが, もっと良い法法がご教授ください

2020-08-30 11:55 UTC, higurashi-takuto requested changes
コメントしましたー

2020-08-30 11:55 UTC, higurashi-takuto commented on src/renderer/reducks/editor/reducers.js
> +      if (deletedDocumentId !== activeDocumentId) {
158行目の `if` は `return` するから確かにこれでも動くんですが、一つの処理をする判定だとわかりにくいので、この `if` と次の `if` は `else if` でつなげましょう。

2020-08-30 11:55 UTC, higurashi-takuto commented on src/renderer/reducks/editor/utils.js
> +};
名前が `getDocument` なのに、ドキュメントとインデックスの2つを戻しているので、名前が合っていないですね。
ちょっとまだ、どれがいいか判断できないけど
- 名前を `getDocumentAndIndex` にする。
- `getDocumentIndex(editor, documentId)` と `getDocument(editor, documentIndex)`
- `getDocumentIndex(editor, documentId)` にして、ドキュメントを取る分には `const document = documents[documentIndex]` にする。

2つ目に関しては getDocument が他にも使われていきそうなら `getDocumentFromId` と `getDocumentFromIndex` があっても良いかも？

2020-08-30 11:57 UTC, higurashi-takuto commented on src/renderer/reducks/editor/selectors.js
> +import * as utils from './utils';
明確に分けるならこれぐらいしか無いよね。
難しい…

2020-08-30 12:03 UTC, Sota-Watanabe commented on src/renderer/reducks/editor/reducers.js
> +      if (deletedDocumentId !== activeDocumentId) {
僕も同意見なのですがeslint君が怒るのでそのような実装になりました. 

https://eslint.org/docs/rules/no-else-return

2020-08-30 12:09 UTC, Sota-Watanabe commented on src/renderer/reducks/editor/utils.js
> +};
一度2つ目の実装を行ったのですが, ほぼ全部const document = documents[documentsIndex]をやっていたので無駄かなと思い, このような実装にしました. 

でも確かに名前があっていないですね. 

直近にgetDocumentが他に使われるのが思いつかないので
個人的には1つ目のgetDocumentAndIndexにしたいと思いますがいいでしょうか.

2020-08-30 12:32 UTC, higurashi-takuto commented on src/renderer/reducks/editor/utils.js
> +};
確かに直近では使わないかもしれないけど、今後開発していくことを考えると `getDocumentAndIndex` を作ったとしても、内部的には `getDocumentIndex` と `getDocument` の2つを呼び出すようにしておいた方が汎用的なのでそれが良いかもしれません。
それをするぐらいならまんま2つ目でも良い気がしますが…
まあ、どっちにするかはお任せします！

2020-08-30 13:03 UTC, Sota-Watanabe commented
getDocument->getDocumentAndIndexに変更しました.

2020-08-31 06:55 UTC, higurashi-takuto commented on src/renderer/reducks/editor/reducers.js
> +      if (deletedDocumentId !== activeDocumentId) {
これ一旦、ESLint 無視するように指定して、今度全体の ESLint の設定の変更をしよう（ named import とこれ 他にもあればそれも ） 。

2020-08-31 07:02 UTC, merged