TitleBarにActiveDocumentのFileNameとFilePathを表示
cdlab-sit/XenonText pull request #67
Opened 2020-09-18 09:56 UTC by takuya-shibaura-it

#19 TitleBarにActiveDocumentのファイル名を表示するよう機能追加

2020-09-18 17:11 UTC, Sota-Watanabe commented on src/renderer/components/TitleBar.jsx
> +        activeDocument.filePath.length - activeDocument.fileName.length;
好みかもしれませんが、
```
const pathLength = activeDocument.filePath.lastIndexOf('/');
```
lastIndexOfを使った方がわかりやすいと思います。

2020-09-18 18:20 UTC, higurashi-takuto requested changes
2点コメントしました。

2020-09-18 18:20 UTC, higurashi-takuto commented on src/renderer/components/TitleBar.jsx
> +  const title = activeDocument ? activeDocument.fileName : 'XenonText';
デフォルト値の `XenonText` はエレクトロンのアプリ名から取得する方が良いですね。

参考↓
```
import { remote } from 'electron';
const { app } = remote;
app.name    ← XenonText が入ってる
```

2020-09-18 18:20 UTC, higurashi-takuto commented on src/renderer/components/TitleBar.jsx
> +      return ` - ${activeDocument.filePath.substr(0, pathLength)}`;
ハイフン `-` じゃなくて en ダッシュ `–` の方が用法的に自然な気がします。

2020-09-18 21:05 UTC, kawapoo commented on src/renderer/components/TitleBar.jsx
> +        activeDocument.filePath.length - activeDocument.fileName.length;
指摘事項には同意しますが、一点だけ懸念点あります。
挙動がわかれば教えて欲しいのですが、Windowsの場合パスの区切り文字ってどうなりますか？
「/」でいいのなら問題はないかと思いますが、「¥」or「\」の場合はFileName部分が消せないことになります。
Electronの仕様だとは思いますが…。

2020-09-19 04:05 UTC, higurashi-takuto commented on src/renderer/components/TitleBar.jsx
> +        activeDocument.filePath.length - activeDocument.fileName.length;
あ、そうそう、これいずれ確認しようと思ってたんだよね。
他にも `/` に依存してる場所があるから https://github.com/cdlab-sit/XenonText/blob/f2d7625fb9624afef53f3f28c0e1fbde2f276130/src/renderer/reducks/editor/reducers.js#L48

2020-09-19 04:55 UTC, kawapoo commented
指摘事項について全て反映完了しました

2020-09-19 05:41 UTC, Sota-Watanabe approved these changes

2020-09-21 17:59 UTC, merged