サイドバー内でのスクロール機能追加
cdlab-sit/XenonText pull request #75
Opened 2020-09-29 14:48 UTC by Sota-Watanabe

開くファイルが増えた場合、サイドバー内でスクロールする機能を追加しました

2020-09-30 05:31 UTC, higurashi-takuto requested changes
2点書きましたー。
高さの方はなんか良い感じの解決方法思いついたら言いますね。

2020-09-30 05:31 UTC, higurashi-takuto commented on src/renderer/components/SideBar.jsx
> +    <div className="w-full flex flex-col flex-auto mt-10 overflow-scroll">
こっちの `overflow-scroll` はいらないかな

2020-09-30 05:31 UTC, higurashi-takuto commented on src/renderer/components/Body.jsx
> +          height: 'calc(100vh - 3rem)',
この指定だとタイトルバー非表示時（ macOS のフルスクリーン時 ）に意図しない表示になります。

2020-09-30 13:58 UTC, Sota-Watanabe commented
修正を行いました。
確認お願いします。

2020-10-01 06:26 UTC, higurashi-takuto commented
動作はあってるんだけど、なんでこれで動いてるの…？

2020-10-04 14:50 UTC, merged